"""new

Revision ID: 0c95f775a43e
Revises: 36ade1496c8d
Create Date: 2025-04-20 06:29:31.799631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c95f775a43e'
down_revision = '36ade1496c8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insurance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insurance_con_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'insurance_con', ['insurance_con_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insurance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('insurance_con_id')

    # ### end Alembic commands ###
