"""empty message

Revision ID: 99af0df167bc
Revises: 0c95f775a43e
Create Date: 2025-04-21 19:48:00.888622

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '99af0df167bc'
down_revision = '0c95f775a43e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_plan')
    with op.batch_alter_table('live', schema=None) as batch_op:
        batch_op.drop_index('ix_live_username')

    op.drop_table('live')
    with op.batch_alter_table('user_phone_number', schema=None) as batch_op:
        batch_op.drop_index('ix_user_phone_number_username')

    op.drop_table('user_phone_number')
    with op.batch_alter_table('end_date', schema=None) as batch_op:
        batch_op.drop_index('ix_end_date_username')

    op.drop_table('end_date')
    with op.batch_alter_table('start_date', schema=None) as batch_op:
        batch_op.drop_index('ix_start_date_username')

    op.drop_table('start_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('start_date',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='start_date_pkey')
    )
    with op.batch_alter_table('start_date', schema=None) as batch_op:
        batch_op.create_index('ix_start_date_username', ['username'], unique=False)

    op.create_table('end_date',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('End_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='end_date_pkey')
    )
    with op.batch_alter_table('end_date', schema=None) as batch_op:
        batch_op.create_index('ix_end_date_username', ['username'], unique=False)

    op.create_table('user_phone_number',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_phone_number_pkey'),
    sa.UniqueConstraint('phone_number', name='user_phone_number_phone_number_key')
    )
    with op.batch_alter_table('user_phone_number', schema=None) as batch_op:
        batch_op.create_index('ix_user_phone_number_username', ['username'], unique=False)

    op.create_table('live',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('live', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='live_pkey')
    )
    with op.batch_alter_table('live', schema=None) as batch_op:
        batch_op.create_index('ix_live_username', ['username'], unique=False)

    op.create_table('purchase_plan',
    sa.Column('id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('Purchase_plan', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='purchase_plan_pkey')
    )
    # ### end Alembic commands ###
