"""empty message

Revision ID: a61a4e163b53
Revises: e1bc8f29dc96
Create Date: 2025-04-19 20:25:33.389125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a61a4e163b53'
down_revision = 'e1bc8f29dc96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('end_date', schema=None) as batch_op:
        batch_op.drop_constraint('end_date_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('live', schema=None) as batch_op:
        batch_op.drop_constraint('live_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('purchase_plan', schema=None) as batch_op:
        batch_op.drop_constraint('purchase_plan_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('start_date', schema=None) as batch_op:
        batch_op.drop_constraint('start_date_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user_phone_number', schema=None) as batch_op:
        batch_op.drop_constraint('user_phone_number_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_phone_number', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_phone_number_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('start_date', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('start_date_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('purchase_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('purchase_plan_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('live', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('live_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('end_date', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('end_date_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
