"""empty message

Revision ID: e1bc8f29dc96
Revises: cd3561ae6c98
Create Date: 2025-04-19 19:22:30.930714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e1bc8f29dc96'
down_revision = 'cd3561ae6c98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('end_date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('End_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('end_date', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_end_date_username'), ['username'], unique=True)

    op.create_table('live',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('live', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('live', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_live_username'), ['username'], unique=True)

    op.create_table('purchase_plan',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('Purchase_plan', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('start_date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('start_date', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_start_date_username'), ['username'], unique=True)

    op.create_table('user_phone_number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    with op.batch_alter_table('user_phone_number', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_phone_number_username'), ['username'], unique=True)

    op.drop_table('courtesy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courtesy',
    sa.Column('id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('Courtesy_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('End_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='courtesy_pkey')
    )
    with op.batch_alter_table('user_phone_number', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_phone_number_username'))

    op.drop_table('user_phone_number')
    with op.batch_alter_table('start_date', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_start_date_username'))

    op.drop_table('start_date')
    op.drop_table('purchase_plan')
    with op.batch_alter_table('live', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_live_username'))

    op.drop_table('live')
    with op.batch_alter_table('end_date', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_end_date_username'))

    op.drop_table('end_date')
    # ### end Alembic commands ###
