"""empty message

Revision ID: fcdc14dde447
Revises: 0c95f775a43e
Create Date: 2025-04-20 19:15:36.616652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcdc14dde447'
down_revision = '0c95f775a43e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insurance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.String(length=50), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('name')

    with op.batch_alter_table('insurance_con', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=220),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insurance_con', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.String(length=220),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('insurance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('body')

    # ### end Alembic commands ###
